server:
  port: 8081

spring:
  application:
      name: interview-server
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/interview?useSSL=false
    username: root
    password: admin123
    driver-class-name: com.mysql.jdbc.Driver

  security:
    basic:
      enabled: false

