version: "2"

services:
  mongo:
    image: mongo
    networks:
      - cms-network
    ports:
      - "27017:27017"
    expose:
      - "27017"
  eureka:
    image: springcloud/eureka
    networks:
      - cms-network
    ports:
      - "8761:8761"
    expose:
      - "8761"

                
networks:
  cms-network:
    driver: bridge
