server:
  port: 8080

spring:
  application:
    name: gateway
  profiles:
    active: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    datasource:
      url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver

  security:
    basic:
      enabled: false


zuul:
  routes:
   skills:
    path: /json/skills/**
    serviceId: skill-server
    stripPrefix: false
   positions:
    path: /json/positions/**
    serviceId: position-server
    stripPrefix: false
   interviews:
    path: /json/interviews/**
    serviceId: interview-server

#   imageman:
#    path: /imageman/**
#    serviceId: imageman
#    stripPrefix: false

